In [16]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_theme(style="whitegrid")

In [17]:
df = pd.read_csv("MI7_GROUNDWATERSCHEME_ASSAM.csv")

print("Dataset shape:", df.shape)
display(df.head())

Dataset shape: (57303, 64)

,serial_no,state_name,district_name,block_tehsil_name,village_name,latitude,longitude,s_no_of_scheme,scheme_type,dugwell_type,...,ipc_total,ipu_kharif_season,ipu_rabi_season,ipu_perennial_crop,ipu_other_season,ipu_total,under_utilised_selection,under_utilisation_reason,drinking_water_purpose,captured_in_previous_census
0,1,ASSAM,Goalpara,Kuchdhowa,Siluk Pt-Ii,25.956992,90.799726,1,Tube well,NaN,...,5.0,4.0,1.0,0.00,0.00,5.00,NaN,NaN,No,No
1,2,ASSAM,Kokrajhar,Kokrajhar,Bhadiaguri,26.355332,90.233585,12,Tube well,NaN,...,1.0,0.4,0.2,0.09,0.08,0.77,NaN,NaN,No,No
2,3,ASSAM,Goalpara,Kuchdhowa,Patiarpara Pt-I,25.971319,90.917621,1,Tube well,NaN,...,4.0,4.0,0.0,0.00,0.00,4.00,NaN,NaN,No,Yes
3,4,ASSAM,Dhubri,Nayeralga,Boalkamri Pt.Iii,26.210017,90.160672,4,Tube well,NaN,...,3.5,2.0,1.5,0.00,0.00,3.50,No,NaN,No,No
4,5,ASSAM,Dhubri,Nayeralga,Boalkamri Pt.Iii,26.208178,90.161543,7,Tube well,NaN,...,4.5,2.5,2.0,0.00,0.00,4.50,No,NaN,No,No

In [18]:
# Strip hidden whitespaces from columns
df.columns = df.columns.str.strip()

# Now drop the columns securely
df = df.drop(columns=['serial_no', 'state_name'])
df.head()

,district_name,block_tehsil_name,village_name,latitude,longitude,s_no_of_scheme,scheme_type,dugwell_type,tubewell_type,ownership,...,ipc_total,ipu_kharif_season,ipu_rabi_season,ipu_perennial_crop,ipu_other_season,ipu_total,under_utilised_selection,under_utilisation_reason,drinking_water_purpose,captured_in_previous_census
0,Goalpara,Kuchdhowa,Siluk Pt-Ii,25.956992,90.799726,1,Tube well,NaN,Medium Tube well,Govt. Owned,...,5.0,4.0,1.0,0.00,0.00,5.00,NaN,NaN,No,No
1,Kokrajhar,Kokrajhar,Bhadiaguri,26.355332,90.233585,12,Tube well,NaN,Shallow Tube well,Govt. Owned,...,1.0,0.4,0.2,0.09,0.08,0.77,NaN,NaN,No,No
2,Goalpara,Kuchdhowa,Patiarpara Pt-I,25.971319,90.917621,1,Tube well,NaN,Medium Tube well,Govt. Owned,...,4.0,4.0,0.0,0.00,0.00,4.00,NaN,NaN,No,Yes
3,Dhubri,Nayeralga,Boalkamri Pt.Iii,26.210017,90.160672,4,Tube well,NaN,Shallow Tube well,Owned by individual farmer,...,3.5,2.0,1.5,0.00,0.00,3.50,No,NaN,No,No
4,Dhubri,Nayeralga,Boalkamri Pt.Iii,26.208178,90.161543,7,Tube well,NaN,Shallow Tube well,Owned by individual farmer,...,4.5,2.5,2.0,0.00,0.00,4.50,No,NaN,No,No