# Import Dataset

In [1]:
import numpy as np
import pandas as pd

df = pd.read_csv("MI7_GROUNDWATERSCHEME_ASSAM.csv")
df.head()

,serial_no,state_name,district_name,block_tehsil_name,village_name,latitude,longitude,s_no_of_scheme,scheme_type,dugwell_type,...,ipc_total,ipu_kharif_season,ipu_rabi_season,ipu_perennial_crop,ipu_other_season,ipu_total,under_utilised_selection,under_utilisation_reason,drinking_water_purpose,captured_in_previous_census
0,1,ASSAM,Goalpara,Kuchdhowa,Siluk Pt-Ii,25.956992,90.799726,1,Tube well,NaN,...,5.0,4.0,1.0,0.00,0.00,5.00,NaN,NaN,No,No
1,2,ASSAM,Kokrajhar,Kokrajhar,Bhadiaguri,26.355332,90.233585,12,Tube well,NaN,...,1.0,0.4,0.2,0.09,0.08,0.77,NaN,NaN,No,No
2,3,ASSAM,Goalpara,Kuchdhowa,Patiarpara Pt-I,25.971319,90.917621,1,Tube well,NaN,...,4.0,4.0,0.0,0.00,0.00,4.00,NaN,NaN,No,Yes
3,4,ASSAM,Dhubri,Nayeralga,Boalkamri Pt.Iii,26.210017,90.160672,4,Tube well,NaN,...,3.5,2.0,1.5,0.00,0.00,3.50,No,NaN,No,No
4,5,ASSAM,Dhubri,Nayeralga,Boalkamri Pt.Iii,26.208178,90.161543,7,Tube well,NaN,...,4.5,2.5,2.0,0.00,0.00,4.50,No,NaN,No,No

In [2]:
df.shape

(57303, 64)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 57303 entries, 0 to 57302
Data columns (total 64 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   serial_no                           57303 non-null  int64
 1   state_name                          57303 non-null  object
 2   district_name                       57303 non-null  object
 3   block_tehsil_name                   57303 non-null  object
 4   village_name                        57303 non-null  object
 5   latitude                            57303 non-null  float64
 6   longitude                           57303 non-null  float64
 7   s_no_of_scheme                      57303 non-null  int64
 8   scheme_type                         57303 non-null  object
 9   dugwell_type                        809 non-null    object
 10  tubewell_type                       56494 non-null  object
 11  ownership                           57303 non-null  object
 12  khasra_number                       24023 non-null  object
 13  location_particulars                51320 non-null  object
 14  total_owners_holding                57303 non-null  float64
 15  social_status                       41361 non-null  object
 16  gender                              41361 non-null  object
 17  commissioning_year                  57303 non-null  object
 18  scheme_depth                        57303 non-null  float64
 19  scheme_diameter                     54149 non-null  float64
 20  scheme_bore_depth                   57303 non-null  float64
 21  nearest_scheme_distance             57303 non-null  float64
 22  construction_cost                   57303 non-null  float64
 23  machinery_cost                      57303 non-null  float64
 24  maintenance_cost                    57303 non-null  float64
 25  finance_source1                     41334 non-null  object
 26  finance_source2                     33615 non-null  object
 27  construction_subsidy                57303 non-null  float64
 28  machinery_subsidy                   57303 non-null  float64
 29  scheme_status                       57303 non-null  object
 30  not_in_use_years                    6109 non-null   float64
 31  status_reason_temporarily           5342 non-null   object
 32  status_reason_permanently           767 non-null    object
 33  water_distribution_method           56536 non-null  object
 34  lifting_device_type                 56555 non-null  object
 35  energy_source                       56555 non-null  object
 36  horse_power_of_lifting_device       55384 non-null  float64
 37  pump_operating_days_kharif_season   55396 non-null  float64
 38  pump_operating_days_rabi_season     55396 non-null  float64
 39  pump_operating_days_perennial_crop  55396 non-null  float64
 40  pump_operating_days_other_season    55396 non-null  float64
 41  avg_pumping_per_day_kharif_season   55396 non-null  float64
 42  avg_pumping_per_day_rabi_season     55396 non-null  float64
 43  avg_pumping_per_day_perennial_crop  55396 non-null  float64
 44  avg_pumping_per_day_other_season    55395 non-null  float64
 45  located_in_command_area             57303 non-null  object
 46  name_of_mmi_project                 161 non-null    object
 47  scheme_in_command_area_reason       146 non-null    object
 48  only_recharge_ground_water          57303 non-null  object
 49  culturable_command_area             57303 non-null  float64
 50  ipc_kharif_season                   57303 non-null  float64
 51  ipc_rabi_season                     57303 non-null  float64
 52  ipc_perennial_crop                  57303 non-null  float64
 53  ipc_other_season                    57303 non-null  float64
 54  ipc_total                           57303 non-null  float64
 55  ipu_kharif_season                   57303 non-null  float64
 56  ipu_rabi_season                     57303 non-null  float64
 57  ipu_perennial_crop                  57303 non-null  float64
 58  ipu_other_season                    57303 non-null  float64
 59  ipu_total                           57303 non-null  float64
 60  under_utilised_selection            51264 non-null  object
 61  under_utilisation_reason            8546 non-null   object
 62  drinking_water_purpose              57303 non-null  object
 63  captured_in_previous_census         56466 non-null  object
dtypes: float64(33), int64(2), object(29)
memory usage: 28.0+ MB

In [4]:
df.describe()

,serial_no,latitude,longitude,s_no_of_scheme,total_owners_holding,scheme_depth,scheme_diameter,scheme_bore_depth,nearest_scheme_distance,construction_cost,...,ipc_kharif_season,ipc_rabi_season,ipc_perennial_crop,ipc_other_season,ipc_total,ipu_kharif_season,ipu_rabi_season,ipu_perennial_crop,ipu_other_season,ipu_total
count,57303.000000,57303.000000,57303.000000,57303.000000,57303.000000,57303.000000,54149.000000,57303.000000,57303.000000,5.730300e+04,...,57303.000000,57303.000000,57303.000000,57303.000000,57303.000000,57303.000000,57303.000000,57303.000000,57303.000000,57303.000000
mean,28652.000000,26.314407,91.459174,11.900215,1.557596,27.468942,85.076435,0.231128,205.604155,1.577646e+05,...,2.155317,1.941574,0.174485,0.375635,4.647010,1.801973,1.587813,0.153559,0.288059,3.831123
std,16542.095575,0.422958,1.447504,17.412754,45.359578,17.318626,405.582533,5.276484,180.272319,6.753971e+05,...,4.032863,2.717230,2.885272,4.587932,8.718665,3.275841,1.934804,2.850640,4.536090,7.500362
min,1.000000,24.269978,89.702887,1.000000,0.000000,0.030000,0.000000,0.000000,0.010000,0.000000e+00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,14326.500000,26.129345,90.186019,2.000000,0.000000,18.000000,3.000000,0.000000,100.000000,1.000000e+04,...,0.666000,1.000000,0.000000,0.000000,2.000000,0.500000,1.000000,0.000000,0.000000,1.800000
50%,28652.000000,26.288032,91.030726,6.000000,1.000000,24.000000,80.000000,0.000000,125.000000,1.500000e+04,...,1.500000,1.500000,0.000000,0.000000,3.500000,1.000000,1.200000,0.000000,0.000000,3.000000
75%,42977.500000,26.437511,92.381378,14.000000,2.000000,35.000000,100.000000,0.000000,300.000000,3.500000e+04,...,2.100000,2.000000,0.000000,0.200000,5.000000,2.000000,2.000000,0.000000,0.100000,4.400000
max,57303.000000,27.972524,95.889462,221.000000,9000.000000,800.000000,35000.000000,450.000000,5001.000000,5.000000e+07,...,250.000000,122.000000,250.000000,750.000000,750.000000,250.000000,122.000000,250.000000,750.000000,750.000000

# Handling Missing values

In [5]:
missing_df = pd.DataFrame({
    "Missing_Count": df.isnull().sum(),
    "Missing_Percentage": (df.isnull().sum() / len(df)) * 100
})

missing_df = missing_df.sort_values(
    by="Missing_Percentage",
    ascending=False
)

missing_df.head(10)

                               Missing_Count  Missing_Percentage
scheme_in_command_area_reason          57157           99.745214
name_of_mmi_project                    57142           99.719037
status_reason_permanently              56536           98.661501
dugwell_type                           56494           98.588207
status_reason_temporarily              51961           90.677626
not_in_use_years                       51194           89.339127
under_utilisation_reason               48757           85.086296
khasra_number                          33280           58.077239
finance_source2                        23688           41.338150
finance_source1                        15969           27.867651

# Data types

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 57303 entries, 0 to 57302
Data columns (total 64 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   serial_no                           57303 non-null  int64
 1   state_name                          57303 non-null  object
 2   district_name                       57303 non-null  object
 3   block_tehsil_name                   57303 non-null  object
 4   village_name                        57303 non-null  object
 5   latitude                            57303 non-null  float64
 6   longitude                           57303 non-null  float64
 7   s_no_of_scheme                      57303 non-null  int64
 8   scheme_type                         57303 non-null  object
 9   dugwell_type                        809 non-null    object
 10  tubewell_type                       56494 non-null  object
 11  ownership                           57303 non-null  object
 12  khasra_number                       24023 non-null  object
 13  location_particulars                51320 non-null  object
 14  total_owners_holding                57303 non-null  float64
 15  social_status                       41361 non-null  object
 16  gender                              41361 non-null  object
 17  commissioning_year                  57303 non-null  object
 18  scheme_depth                        57303 non-null  float64
 19  scheme_diameter                     54149 non-null  float64
 20  scheme_bore_depth                   57303 non-null  float64
 21  nearest_scheme_distance             57303 non-null  float64
 22  construction_cost                   57303 non-null  float64
 23  machinery_cost                      57303 non-null  float64
 24  maintenance_cost                    57303 non-null  float64
 25  finance_source1                     41334 non-null  object
 26  finance_source2                     33615 non-null  object
 27  construction_subsidy                57303 non-null  float64
 28  machinery_subsidy                   57303 non-null  float64
 29  scheme_status                       57303 non-null  object
 30  not_in_use_years                    6109 non-null   float64
 31  status_reason_temporarily           5342 non-null   object
 32  status_reason_permanently           767 non-null    object
 33  water_distribution_method           56536 non-null  object
 34  lifting_device_type                 56555 non-null  object
 35  energy_source                       56555 non-null  object
 36  horse_power_of_lifting_device       55384 non-null  float64
 37  pump_operating_days_kharif_season   55396 non-null  float64
 38  pump_operating_days_rabi_season     55396 non-null  float64
 39  pump_operating_days_perennial_crop  55396 non-null  float64
 40  pump_operating_days_other_season    55396 non-null  float64
 41  avg_pumping_per_day_kharif_season   55396 non-null  float64
 42  avg_pumping_per_day_rabi_season     55396 non-null  float64
 43  avg_pumping_per_day_perennial_crop  55396 non-null  float64
 44  avg_pumping_per_day_other_season    55395 non-null  float64
 45  located_in_command_area             57303 non-null  object
 46  name_of_mmi_project                 161 non-null    object
 47  scheme_in_command_area_reason       146 non-null    object
 48  only_recharge_ground_water          57303 non-null  object
 49  culturable_command_area             57303 non-null  float64
 50  ipc_kharif_season                   57303 non-null  float64
 51  ipc_rabi_season                     57303 non-null  float64
 52  ipc_perennial_crop                  57303 non-null  float64
 53  ipc_other_season                    57303 non-null  float64
 54  ipc_total                           57303 non-null  float64
 55  ipu_kharif_season                   57303 non-null  float64
 56  ipu_rabi_season                     57303 non-null  float64
 57  ipu_perennial_crop                  57303 non-null  float64
 58  ipu_other_season                    57303 non-null  float64
 59  ipu_total                           57303 non-null  float64
 60  under_utilised_selection            51264 non-null  object
 61  under_utilisation_reason            8546 non-null   object
 62  drinking_water_purpose              57303 non-null  object
 63  captured_in_previous_census         56466 non-null  object
dtypes: float64(33), int64(2), object(29)
memory usage: 28.0+ MB

In [7]:
print(df["state_name"].value_counts(dropna=False))

state_name
ASSAM    57303
Name: count, dtype: int64

In [8]:
df.drop(columns=["state_name"], inplace=True)

In [9]:
print(df["district_name"].value_counts(dropna=False))

district_name
Dhubri                     14841
Barpeta                    10315
Marigaon                    5020
Bongaigaon                  2922
Kamrup                      2285
Goalpara                    2273
Nagaon                      2160
Darrang                     2104
Golaghat                    1272
Lakhimpur                   1201
Kokrajhar                   1149
Cachar                      1067
Sonitpur                    1064
Tinsukia                     962
Hojai                        927
Karbi Anglong                830
Nalbari                      784
Dibrugarh                    653
Bajali                       652
Chirang                      625
Biswanath                    617
Jorhat                       560
Dhemaji                      385
South Salmara Mancachar      385
Sivasagar                    348
Karimganj                    339
Baksa                        338
Hailakandi                   233
Charaideo                    227
Majuli                       224
Udalguri                     179
West Karbi Anglong           168
Tamulpur                     132
Kamrup Metro                  62
Name: count, dtype: int64

In [10]:
print(df["block_tehsil_name"].value_counts(dropna=False))

block_tehsil_name
Mandia                 3429
Debitola               2475
Gauripur               2291
Mahamaya               2114
Pakabetbari            1791
                       ...
Kapili Pt.I               2
Chinthong                 2
Bongaon                   2
Batabraba (Part)          1
Chapor-Salkocha-Btc       1
Name: count, Length: 227, dtype: int64

In [11]:
col = "latitude"

print("Column:", col)
print("Data type:", df[col].dtype)
print(df[col].value_counts(dropna=False).head(20))

Column: latitude
Data type: float64
latitude
26.313813    13
26.034514    12
26.448284    12
26.238670    10
24.930547    10
26.976792     9
26.102358     9
26.251230     9
26.264147     9
26.286045     9
26.465390     9
26.167782     8
26.006658     8
26.413214     8
27.138448     8
26.314112     8
26.348714     7
26.409999     7
26.265316     7
25.700665     7
Name: count, dtype: int64

In [12]:
col = "longitude"

print("Column:", col)
print("Data type:", df[col].dtype)
print(df[col].value_counts(dropna=False).head(20))

Column: longitude
Data type: float64
longitude
90.480240    13
90.176807    12
92.545021    12
92.162062    10
92.536352    10
90.159008    10
92.738888    10
90.167788    10
90.160179    10
94.727689     9
89.975941     9
90.166617     8
90.171593     8
93.063650     8
95.206606     8
92.484992     8
90.480063     8
93.933499     7
91.065046     7
89.873176     7
Name: count, dtype: int64

In [13]:
col = "s_no_of_scheme"

print("Column:", col)
print("Data type:", df[col].dtype)
print("Unique values:", df[col].nunique())
print("Sample values:")
print(df[col].value_counts(dropna=False).head(20))

Column: s_no_of_scheme
Data type: int64
Unique values: 221
Sample values:
s_no_of_scheme
1     8817
2     6046
3     4671
4     3821
5     3241
6     2808
7     2491
8     2205
9     1965
10    1762
11    1588
12    1414
13    1257
14    1137
15    1039
16     946
17     870
18     790
19     728
20     670
Name: count, dtype: int64

In [14]:
col = "scheme_type"

print("Column:", col)
print("Data type:", df[col].dtype)
print("Unique values:", df[col].nunique())
print("Values:")
print(df[col].value_counts(dropna=False))

Column: scheme_type
Data type: object
Unique values: 2
Values:
scheme_type
Tube well    56494
Dug well       809
Name: count, dtype: int64

In [15]:
col = "dugwell_type"

print("Column:", col)
print("Data type:", df[col].dtype)
print("Unique values:", df[col].nunique())
print("Missing values:", df[col].isna().sum())
print("Values:")
print(df[col].value_counts(dropna=False))

Column: dugwell_type
Data type: object
Unique values: 4
Missing values: 56494
Values:
dugwell_type
NaN                  56494
Dug well Pucca         477
Dug well Kutcha        228
Dug-cum-bore well       75
Others                  29
Name: count, dtype: int64

In [16]:
col = "tubewell_type"

print("Column:", col)
print("Data type:", df[col].dtype)
print("Unique values:", df[col].nunique())
print("Missing values:", df[col].isna().sum())
print("Values:")
print(df[col].value_counts(dropna=False))

# has null values

Column: tubewell_type
Data type: object
Unique values: 4
Missing values: 809
Values:
tubewell_type
Shallow Tube well    47322
Medium Tube well      7761
Deep Tube well        1389
NaN                    809
Artesian Well           22
Name: count, dtype: int64

In [17]:
col = "ownership"

print("Column:", col)
print("Data type:", df[col].dtype)
print("Unique values:", df[col].nunique())
print("Missing values:", df[col].isna().sum())
print("Values:")
print(df[col].value_counts(dropna=False))

Column: ownership
Data type: object
Unique values: 6
Missing values: 0
Values:
ownership
Owned by individual farmer    41242
Govt. Owned                   10014
Owned by Group of farmers      3242
Others                         2582
Co-Operative Owned              138
Panchayat Owned                  85
Name: count, dtype: int64

## Converting khasra_number into int

In [18]:
col = "khasra_number"

print("Column:", col)
print("Data type:", df[col].dtype)
print("Unique values:", df[col].nunique())
print("Missing values:", df[col].isna().sum())
print("Sample values:")
print(df[col].value_counts(dropna=False).head(20))

Column: khasra_number
Data type: object
Unique values: 2180
Missing values: 33280
Sample values:
khasra_number
NaN     33280
na       8265
Na       2906
1        2111
NA       1317
0         572
na        562
2         444
3         311
4         272
NS        258
5         240
6         224
N A       193
7         184
 N A      179
8         160
9         142
10        137
11        121
Name: count, dtype: int64

In [19]:
col = "khasra_number"

# Treat missing-value placeholders as NaN
df[col] = df[col].astype("string").str.strip()
df[col] = df[col].replace(
    r"(?i)^(na|n a|ns|nan|)$", pd.NA, regex=True
)

# Convert numeric values to numbers
df[col] = pd.to_numeric(df[col], errors="coerce")

# Check whether all remaining values are whole numbers
print("Non-integer values:",
      ((df[col].dropna() % 1) != 0).sum())

# Convert to nullable integer if all values are whole numbers
if ((df[col].dropna() % 1) == 0).all():
    df[col] = df[col].astype("Int64")

print("New data type:", df[col].dtype)
print(df[col].value_counts(dropna=False).head(20))

Non-integer values: 0
New data type: Int64
khasra_number
<NA>    49735
1        2111
0         572
2         444
3         311
4         272
5         240
6         224
7         184
8         160
9         142
10        137
11        121
12        111
14         92
13         82
15         77
16         69
17         51
19         46
Name: count, dtype: Int64

In [20]:
df["khasra_number"] = df["khasra_number"].astype("Int64")

In [21]:
col = "location_particulars"

print("Column:", col)
print("Data type:", df[col].dtype)
print("Unique values:", df[col].nunique())
print("Missing values:", df[col].isna().sum())
print("Sample values:")
print(df[col].value_counts(dropna=False).head(20))

# Needs Processign

Column: location_particulars
Data type: object
Unique values: 20021
Missing values: 5983
Sample values:
location_particulars
NaN                  5983
na                   2678
A                    1409
in filled             736
near home             524
near road             511
near house            477
NA                    463
Na                    433
NEAR PADDY FIELD      353
NEAR LP SCHOOL        342
near JJM PHE          314
in paddy              310
NEAR PWD ROAD         267
0                     256
near paddy field      253
NEAR MASJID           240
VILLAGE               230
near house            230
near road             223
Name: count, dtype: int64

In [22]:
col = "total_owners_holding"

print("Column:", col)
print("Data type:", df[col].dtype)
print("Unique values:", df[col].nunique())
print("Missing values:", df[col].isna().sum())
print("Sample values:")
print(df[col].value_counts(dropna=False).head(20))

Column: total_owners_holding
Data type: float64
Unique values: 305
Missing values: 0
Sample values:
total_owners_holding
1.00    16425
0.00    16061
2.00     9209
3.00     2053
1.50     1697
4.00     1616
0.50     1018
5.00      967
0.80      551
1.33      438
0.40      434
1.20      429
0.53      414
0.66      347
6.00      341
0.60      335
0.26      265
2.50      259
1.30      224
0.70      208
Name: count, dtype: int64

In [23]:
col = "social_status"

print("Column:", col)
print("Data type:", df[col].dtype)
print("Unique values:", df[col].nunique())
print("Missing values:", df[col].isna().sum())
print(df[col].value_counts(dropna=False).head(20))

# Needs Processing

Column: social_status
Data type: object
Unique values: 4
Missing values: 15942
social_status
Others             31977
NaN                15942
OBC                 4455
Scheduled-tribe     2975
Scheduled-caste     1954
Name: count, dtype: int64

In [24]:
col = "gender"

print("Column:", col)
print("Data type:", df[col].dtype)
print("Unique values:", df[col].nunique())
print("Missing values:", df[col].isna().sum())
print(df[col].value_counts(dropna=False).head(20))

# Process

Column: gender
Data type: object
Unique values: 3
Missing values: 15942
gender
Male           40784
NaN            15942
Female           565
Transgender       12
Name: count, dtype: int64

In [25]:
col = "commissioning_year"

print("Column:", col)
print("Data type:", df[col].dtype)
print("Unique values:", df[col].nunique())
print("Missing values:", df[col].isna().sum())
print(df[col].value_counts(dropna=False).head(20))

Column: commissioning_year
Data type: object
Unique values: 6
Missing values: 0
commissioning_year
Up to 2018-2019     22215
During 2019-2020    11750
During 2020-2021     9626
During 2021-2022     7129
During 2022-2023     3534
During 2023-2024     3049
Name: count, dtype: int64

In [26]:
col = "scheme_depth"

print("Column:", col)
print("Data type:", df[col].dtype)
print("Unique values:", df[col].nunique())
print("Missing values:", df[col].isna().sum())
print(df[col].value_counts(dropna=False).head(20))

Column: scheme_depth
Data type: float64
Unique values: 448
Missing values: 0
scheme_depth
20.0    8014
24.0    6816
45.0    5531
35.0    5347
15.0    3782
25.0    3542
18.0    2655
30.0    2534
12.0    1511
21.0    1409
16.0    1402
22.0     996
13.0     937
17.0     833
70.0     739
14.0     669
19.0     527
15.5     523
23.0     422
10.0     369
Name: count, dtype: int64

In [27]:
col = "scheme_diameter"

print("Column:", col)
print("Data type:", df[col].dtype)
print("Unique values:", df[col].nunique())
print("Missing values:", df[col].isna().sum())
print(df[col].value_counts(dropna=False).head(20))

Column: scheme_diameter
Data type: float64
Unique values: 296
Missing values: 3154
scheme_diameter
100.00    13635
75.00      6823
80.00      5865
150.00     5518
0.08       3298
NaN        3154
0.10       2811
0.15       2509
0.07       1430
76.00      1178
110.00     1058
76.20       792
101.60      746
3.00        624
0.30        537
200.00      517
250.00      380
125.00      339
1.00        301
0.11        247
Name: count, dtype: int64

In [28]:
col = "scheme_bore_depth"

print("Column:", col)
print("Data type:", df[col].dtype)
print("Unique values:", df[col].nunique())
print("Missing values:", df[col].isna().sum())
print(df[col].value_counts(dropna=False).head(20))

Column: scheme_bore_depth
Data type: float64
Unique values: 72
Missing values: 0
scheme_bore_depth
0.00      57028
45.00        42
35.00        33
30.00        17
20.00        16
0.45         15
50.00        14
70.00        10
80.00        10
75.00         9
100.00        6
15.00         6
10.00         5
29.00         5
25.00         5
200.00        4
24.00         3
42.00         3
450.00        3
37.00         2
Name: count, dtype: int64

In [29]:
col = "nearest_scheme_distance"

print("Column:", col)
print("Data type:", df[col].dtype)
print("Unique values:", df[col].nunique())
print("Missing values:", df[col].isna().sum())
print(df[col].value_counts(dropna=False).head(20))

Column: nearest_scheme_distance
Data type: float64
Unique values: 277
Missing values: 0
nearest_scheme_distance
100.0    13341
500.0     8554
200.0     8137
50.0      5052
300.0     3466
150.0     3059
400.0     1576
60.0      1357
30.0      1237
20.0      1236
250.0     1074
80.0      1017
120.0      875
70.0       542
10.0       527
1.0        523
90.0       429
40.0       423
350.0      369
15.0       298
Name: count, dtype: int64

In [30]:
col = "construction_cost"

print("Column:", col)
print("Data type:", df[col].dtype)
print("Unique values:", df[col].nunique())
print("Missing values:", df[col].isna().sum())
print(df[col].value_counts(dropna=False).head(20))

Column: construction_cost
Data type: float64
Unique values: 1271
Missing values: 0
construction_cost
10000.0     6166
12000.0     4642
15000.0     3736
20000.0     3708
5000.0      2847
8000.0      2216
6000.0      1850
25000.0     1845
30000.0     1618
35000.0     1329
9000.0      1238
606000.0    1018
100000.0     768
40000.0      701
7000.0       656
3000.0       605
4000.0       521
473750.0     501
18000.0      501
210000.0     481
Name: count, dtype: int64

In [31]:
col = "machinery_cost"

print("Column:", col)
print("Data type:", df[col].dtype)
print("Unique values:", df[col].nunique())
print("Missing values:", df[col].isna().sum())
print(df[col].value_counts(dropna=False).head(20))

Column: machinery_cost
Data type: float64
Unique values: 1023
Missing values: 0
machinery_cost
15000.0     5301
25000.0     4937
20000.0     4322
10000.0     4253
12000.0     3646
0.0         2159
16000.0     1854
35000.0     1797
8000.0      1618
18000.0     1387
14000.0     1247
9000.0       964
5000.0       949
50000.0      931
30000.0      903
13000.0      788
7000.0       735
187439.0     733
100000.0     691
150000.0     546
Name: count, dtype: int64

In [32]:
col = "maintenance_cost"

print("Column:", col)
print("Data type:", df[col].dtype)
print("Unique values:", df[col].nunique())
print("Missing values:", df[col].isna().sum())
print(df[col].value_counts(dropna=False).head(20))

Column: maintenance_cost
Data type: float64
Unique values: 335
Missing values: 0
maintenance_cost
0.0        32568
2000.0      5508
5000.0      2411
1000.0      2319
3000.0      2091
2500.0      1887
4000.0      1462
500.0       1399
10000.0     1090
1500.0       880
8000.0       644
6000.0       603
3500.0       407
12000.0      358
1200.0       283
7000.0       261
15000.0      236
20000.0      205
9000.0       140
25000.0      137
Name: count, dtype: int64

In [33]:
col = "finance_source1"

print("Column:", col)
print("Data type:", df[col].dtype)
print("Unique values:", df[col].nunique())
print("Missing values:", df[col].isna().sum())
print(df[col].value_counts(dropna=False).head(20))

Column: finance_source1
Data type: object
Unique values: 5
Missing values: 15969
finance_source1
Own savings        34551
NaN                15969
Others              4118
Government fund     2254
Money lender         252
Bank loan            159
Name: count, dtype: int64

In [34]:
col = "finance_source2"

print("Column:", col)
print("Data type:", df[col].dtype)
print("Unique values:", df[col].nunique())
print("Missing values:", df[col].isna().sum())
print(df[col].value_counts(dropna=False).head(20))

Column: finance_source2
Data type: object
Unique values: 5
Missing values: 23688
finance_source2
Others             26572
NaN                23688
Own savings         5297
Money lender         922
Government fund      664
Bank loan            160
Name: count, dtype: int64

In [35]:
col = "construction_subsidy"

print("Column:", col)
print("Data type:", df[col].dtype)
print("Unique values:", df[col].nunique())
print("Missing values:", df[col].isna().sum())
print(df[col].value_counts(dropna=False).head(20))

Column: construction_subsidy
Data type: float64
Unique values: 567
Missing values: 0
construction_subsidy
0.0         47070
5000.0        642
100000.0      544
10000.0       367
3000.0        303
2000.0        229
180000.0      228
12000.0       227
20000.0       224
589000.0      208
123953.0      197
606000.0      195
4000.0        190
30000.0       182
6000.0        165
26715.0       143
50000.0       141
271964.0      134
400000.0      129
312082.0      127
Name: count, dtype: int64

In [36]:
col = "machinery_subsidy"

print("Column:", col)
print("Data type:", df[col].dtype)
print("Unique values:", df[col].nunique())
print("Missing values:", df[col].isna().sum())
print(df[col].value_counts(dropna=False).head(20))

Column: machinery_subsidy
Data type: float64
Unique values: 515
Missing values: 0
machinery_subsidy
0.0         46328
3000.0        605
5000.0        504
100000.0      480
159366.0      404
2000.0        385
10000.0       343
35000.0       310
1000.0        273
150000.0      271
145285.0      248
141105.0      244
50000.0       220
158000.0      210
20000.0       198
4000.0        197
7000.0        189
25000.0       182
8000.0        180
15000.0       162
Name: count, dtype: int64

In [37]:
col = "scheme_status"

print("Column:", col)
print("Data type:", df[col].dtype)
print("Unique values:", df[col].nunique())
print("Missing values:", df[col].isna().sum())
print(df[col].value_counts(dropna=False).head(20))

Column: scheme_status
Data type: object
Unique values: 3
Missing values: 0
scheme_status
In-Use                    51194
Temporarily Not in use     5342
Permanently Not in use      767
Name: count, dtype: int64

In [38]:
col = "not_in_use_years"

print("Column:", col)
print("Data type:", df[col].dtype)
print("Unique values:", df[col].nunique())
print("Missing values:", df[col].isna().sum())
print(df[col].value_counts(dropna=False).head(20))

# needs Processing

Column: not_in_use_years
Data type: float64
Unique values: 7
Missing values: 51194
not_in_use_years
NaN    51194
1.0     2225
2.0     1714
0.0     1408
3.0      240
6.0      221
5.0      198
4.0      103
Name: count, dtype: int64

In [39]:
col = "status_reason_temporarily"

print("Column:", col)
print("Data type:", df[col].dtype)
print("Unique values:", df[col].nunique())
print("Missing values:", df[col].isna().sum())
print(df[col].value_counts(dropna=False).head(20))

Column: status_reason_temporarily
Data type: object
Unique values: 6
Missing values: 51961
status_reason_temporarily
NaN                                        51961
Any other reason                            3332
Mechanical break down                       1196
Non availability of adequate power/fuel      328
Lack of maintenance                          318
Less discharge of water                      165
Non availability of finance                    3
Name: count, dtype: int64

In [40]:
col = "status_reason_permanently"

print("Column:", col)
print("Data type:", df[col].dtype)
print("Unique values:", df[col].nunique())
print("Missing values:", df[col].isna().sum())
print(df[col].value_counts(dropna=False).head(20))

Column: status_reason_permanently
Data type: object
Unique values: 7
Missing values: 56536
status_reason_permanently
NaN                                                56536
Due to other reasons                                 455
Destroyed beyond repair                              251
Dried up                                              36
Due to salinity                                       14
Due to sea water intrusion                             4
Due to industrial effluents                            4
Availability of major medium irrigation project        3
Name: count, dtype: int64

In [41]:
col = "water_distribution_method"

print("Column:", col)
print("Data type:", df[col].dtype)
print("Unique values:", df[col].nunique())
print("Missing values:", df[col].isna().sum())
print(df[col].value_counts(dropna=False).head(20))

Column: water_distribution_method
Data type: object
Unique values: 7
Missing values: 767
water_distribution_method
Surface pipe                             22690
Open Water Channel (unlined / Kutcha)    18596
Other                                    10832
Open Water Channel (lined / Pucca)        2241
Under ground pipe                         2057
NaN                                        767
Sprinkler                                   60
Drip                                        60
Name: count, dtype: int64

In [42]:
col = "lifting_device_type"

print("Column:", col)
print("Data type:", df[col].dtype)
print("Unique values:", df[col].nunique())
print("Missing values:", df[col].isna().sum())
print(df[col].value_counts(dropna=False).head(20))

Column: lifting_device_type
Data type: object
Unique values: 5
Missing values: 748
lifting_device_type
Centrifugal Pump    36890
Submersible pump    11950
Others               4793
Turbine/Jet pump     1806
Manual/animal        1116
NaN                   748
Name: count, dtype: int64

In [43]:
cols = [
    "energy_source",
    "horse_power_of_lifting_device",
    "pump_operating_days_kharif_season",
    "pump_operating_days_rabi_season",
    "pump_operating_days_perennial_crop"
]

for col in cols:
    print(f"\n{'=' * 50}")
    print("Column:", col)
    print("Data type:", df[col].dtype)
    print("Unique values:", df[col].nunique())
    print("Missing values:", df[col].isna().sum())
    print(df[col].value_counts(dropna=False).head(15))

==================================================
Column: energy_source
Data type: object
Unique values: 7
Missing values: 748
energy_source
Diesel           27323
Electric         18689
Solar             8678
Manual/animal     1116
NaN                748
Others             702
Wind Mills          25
Natural             22
Name: count, dtype: int64

==================================================
Column: horse_power_of_lifting_device
Data type: float64
Unique values: 92
Missing values: 1919
horse_power_of_lifting_device
5.0     24491
2.0     14848
3.0     10667
NaN      1919
1.5      1455
7.5       743
4.0       693
1.0       569
20.0      505
2.5       312
3.5       252
10.0      140
15.0      130
7.0       120
30.0       66
Name: count, dtype: int64

==================================================
Column: pump_operating_days_kharif_season
Data type: float64
Unique values: 123
Missing values: 1907
pump_operating_days_kharif_season
30.0    9326
0.0     7480
60.0    6385
20.0    3374
90.0    2513
80.0    2440
40.0    2320
50.0    1963
25.0    1925
NaN     1907
2.0     1756
45.0    1654
10.0    1319
15.0    1204
70.0    1002
Name: count, dtype: int64

==================================================
Column: pump_operating_days_rabi_season
Data type: float64
Unique values: 140
Missing values: 1907
pump_operating_days_rabi_season
60.0     11468
90.0      7074
30.0      3009
50.0      2802
80.0      2583
100.0     2516
0.0       2488
NaN       1907
20.0      1689
40.0      1649
45.0      1632
120.0     1389
2.0       1317
10.0      1308
70.0      1307
Name: count, dtype: int64

==================================================
Column: pump_operating_days_perennial_crop
Data type: float64
Unique values: 72
Missing values: 1907
pump_operating_days_perennial_crop
0.0     49136
NaN      1907
30.0      963
20.0      832
10.0      719
15.0      464
40.0      454
2.0       402
1.0       303
8.0       289
5.0       284
45.0      227
60.0      205
7.0       127
50.0      125
Name: count, dtype: int64

In [44]:
cols = [
    "pump_operating_days_other_season",
    "avg_pumping_per_day_kharif_season",
    "avg_pumping_per_day_rabi_season",
    "avg_pumping_per_day_perennial_crop",
    "avg_pumping_per_day_other_season"
]

for col in cols:
    print(f"\n{'=' * 50}")
    print("Column:", col)
    print("Data type:", df[col].dtype)
    print("Unique values:", df[col].nunique())
    print("Missing values:", df[col].isna().sum())
    print(df[col].value_counts(dropna=False).head(15))

==================================================
Column: pump_operating_days_other_season
Data type: float64
Unique values: 82
Missing values: 1907
pump_operating_days_other_season
0.0     39391
20.0     5056
30.0     1923
10.0     1919
NaN      1907
60.0      878
15.0      802
1.0       781
5.0       562
50.0      451
45.0      442
25.0      319
2.0       318
40.0      293
90.0      247
Name: count, dtype: int64

==================================================
Column: avg_pumping_per_day_kharif_season
Data type: float64
Unique values: 53
Missing values: 1907
avg_pumping_per_day_kharif_season
6.0     12234
3.0      7529
0.0      7477
4.0      7277
5.0      6702
2.0      5314
8.0      4207
7.0      2254
NaN      1907
1.0       891
9.0       461
10.0      450
20.0      117
15.0       95
12.0       93
Name: count, dtype: int64

==================================================
Column: avg_pumping_per_day_rabi_season
Data type: float64
Unique values: 64
Missing values: 1907
avg_pumping_per_day_rabi_season
6.0     12553
5.0      7281
4.0      6582
8.0      6462
3.0      4941
2.0      3781
7.0      3418
0.0      2489
9.0      2383
NaN      1907
10.0     1577
1.0      1430
12.0      812
11.0      806
6.5       209
Name: count, dtype: int64

==================================================
Column: avg_pumping_per_day_perennial_crop
Data type: float64
Unique values: 29
Missing values: 1907
avg_pumping_per_day_perennial_crop
0.0     49135
NaN      1907
2.0      1511
3.0      1304
1.0      1125
4.0      1000
5.0       628
6.0       304
7.0       148
8.0        97
10.0       69
9.0        17
20.0       10
12.0        9
2.5         9
Name: count, dtype: int64

==================================================
Column: avg_pumping_per_day_other_season
Data type: float64
Unique values: 36
Missing values: 1908
avg_pumping_per_day_other_season
0.0     39404
3.0      3398
2.0      3250
6.0      2522
4.0      2127
1.0      1978
NaN      1908
5.0      1380
2.5       581
8.0       251
7.0       200
10.0      104
9.0        37
20.0       29
3.5        25
Name: count, dtype: int64

In [45]:
cols = [
    "located_in_command_area",
    "name_of_mmi_project",
    "scheme_in_command_area_reason",
    "only_recharge_ground_water",
    "culturable_command_area"
]

for col in cols:
    print(f"\n{'=' * 50}")
    print("Column:", col)
    print("Data type:", df[col].dtype)
    print("Unique values:", df[col].nunique())
    print("Missing values:", df[col].isna().sum())
    print(df[col].value_counts(dropna=False).head(15))

==================================================
Column: located_in_command_area
Data type: object
Unique values: 2
Missing values: 0
located_in_command_area
No     57157
Yes      146
Name: count, dtype: int64

==================================================
Column: name_of_mmi_project
Data type: object
Unique values: 24
Missing values: 57142
name_of_mmi_project
NaN                             57142
JAMUNA IRRIGATION SCHEME           55
JAMUNA                             28
BOROLIA                            15
SONAI                              12
AMRENG                              8
BHUMKI FIS                          6
CHAMPAMATI                          5
BOROLIA IRRIGATION SCHEME           4
DHANSIRI IRRIGATION PROJECT         4
SUKLA                               4
RUPAHI                              3
BORDIKORAI IRRIGATION SCHEME        2
DHANSIRI                            2
DEKADONG FIS                        2
Name: count, dtype: int64

==================================================
Column: scheme_in_command_area_reason
Data type: object
Unique values: 4
Missing values: 57157
scheme_in_command_area_reason
NaN                                                         57157
Other reasons                                                  76
Water not available up to field from major/medium scheme       38
Water available but not adequate for irrigation                25
Water available but not useable for irrigation                  7
Name: count, dtype: int64

==================================================
Column: only_recharge_ground_water
Data type: object
Unique values: 2
Missing values: 0
only_recharge_ground_water
No     56143
Yes     1160
Name: count, dtype: int64

==================================================
Column: culturable_command_area
Data type: float64
Unique values: 372
Missing values: 0
culturable_command_area
2.00     15044
4.00     10857
1.00      7842
3.00      5751
1.50      2018
5.00      1925
0.00      1825
0.50       855
10.00      813
2.50       639
6.00       575
1.20       501
0.80       494
1.33       473
0.53       417
Name: count, dtype: int64

In [46]:
cols = [
    "ipc_kharif_season",
    "ipc_rabi_season",
    "ipc_perennial_crop",
    "ipc_other_season",
    "ipc_total"
]

for col in cols:
    print(f"\n{'=' * 50}")
    print("Column:", col)
    print("Data type:", df[col].dtype)
    print("Unique values:", df[col].nunique())
    print("Missing values:", df[col].isna().sum())
    print(df[col].value_counts(dropna=False).head(15))

==================================================
Column: ipc_kharif_season
Data type: float64
Unique values: 283
Missing values: 0
ipc_kharif_season
2.00     12485
1.00      8441
0.00      7750
4.00      6504
3.00      4435
1.50      3285
0.50      2127
1.20      1297
0.66       978
0.40       678
2.50       678
10.00      593
0.80       562
0.90       521
5.00       423
Name: count, dtype: int64

==================================================
Column: ipc_rabi_season
Data type: float64
Unique values: 274
Missing values: 0
ipc_rabi_season
2.0     15156
1.0     12661
4.0      4650
3.0      3949
1.5      3269
0.0      3139
0.5      2116
0.4      1351
1.8       703
2.5       665
0.6       608
0.8       551
1.2       514
10.0      495
0.3       484
Name: count, dtype: int64

==================================================
Column: ipc_perennial_crop
Data type: float64
Unique values: 111
Missing values: 0
ipc_perennial_crop
0.000     51260
1.000      2302
0.500       960
0.100       876
2.000       349
0.300       186
0.133       166
0.200       154
0.800       108
0.400       106
10.000       96
4.000        92
3.000        77
0.250        76
5.000        61
Name: count, dtype: int64

==================================================
Column: ipc_other_season
Data type: float64
Unique values: 161
Missing values: 0
ipc_other_season
0.0    41563
1.0     4604
2.0     2312
0.5     2069
0.1      961
1.5      704
3.0      698
0.2      521
0.8      392
4.0      382
2.5      215
0.3      206
0.9      203
0.4      200
1.2      172
Name: count, dtype: int64

==================================================
Column: ipc_total
Data type: float64
Unique values: 653
Missing values: 0
ipc_total
4.00    8962
2.00    6383
3.00    5411
6.00    4782
8.00    4236
5.00    3455
1.00    3040
0.00    1833
7.00    1197
3.50    1193
1.50     946
2.50     751
1.26     707
4.50     678
9.00     545
Name: count, dtype: int64

In [47]:
cols = [
    "ipu_kharif_season",
    "ipu_rabi_season",
    "ipu_perennial_crop",
    "ipu_other_season",
    "ipu_total"
]

for col in cols:
    print(f"\n{'=' * 50}")
    print("Column:", col)
    print("Data type:", df[col].dtype)
    print("Unique values:", df[col].nunique())
    print("Missing values:", df[col].isna().sum())
    print(df[col].value_counts(dropna=False).head(15))

==================================================
Column: ipu_kharif_season
Data type: float64
Unique values: 272
Missing values: 0
ipu_kharif_season
2.0     10357
1.0      9986
0.0      9516
4.0      5036
3.0      3800
1.5      3309
0.5      2311
1.2      1409
0.4      1029
0.6      1027
0.8       758
2.5       697
10.0      498
0.9       495
1.8       446
Name: count, dtype: int64

==================================================
Column: ipu_rabi_season
Data type: float64
Unique values: 270
Missing values: 0
ipu_rabi_season
1.0    13970
2.0    12514
0.0     4714
3.0     3699
1.5     3619
0.5     2345
4.0     2213
1.8     1795
0.4     1467
1.2      899
0.8      648
0.6      635
2.5      592
0.3      502
0.2      456
Name: count, dtype: int64

==================================================
Column: ipu_perennial_crop
Data type: float64
Unique values: 119
Missing values: 0
ipu_perennial_crop
0.000     51596
1.000      2133
0.500       947
0.100       901
2.000       261
0.300       206
0.400       202
0.200       189
0.133       168
10.000       85
3.000        54
0.130        43
5.000        39
0.600        34
4.000        34
Name: count, dtype: int64

==================================================
Column: ipu_other_season
Data type: float64
Unique values: 163
Missing values: 0
ipu_other_season
0.00    42599
1.00     4114
0.50     2840
2.00     1182
0.10     1004
1.50      627
0.20      599
0.40      420
0.80      399
0.30      310
3.00      279
1.20      206
2.60      175
0.66      174
2.50      138
Name: count, dtype: int64

==================================================
Column: ipu_total
Data type: float64
Unique values: 690
Missing values: 0
ipu_total
4.0    8208
2.0    6695
3.0    5455
5.0    3831
0.0    3255
6.0    3229
1.0    3012
8.0    1823
2.5    1296
7.0    1255
3.5    1160
1.5    1122
1.2     914
3.3     723
4.5     685
Name: count, dtype: int64

In [48]:
cols = [
    "under_utilised_selection",
    "under_utilisation_reason",
    "drinking_water_purpose",
    "captured_in_previous_census"
]

for col in cols:
    print(f"\n{'=' * 50}")
    print("Column:", col)
    print("Data type:", df[col].dtype)
    print("Unique values:", df[col].nunique())
    print("Missing values:", df[col].isna().sum())
    print(df[col].value_counts(dropna=False).head(15))

==================================================
Column: under_utilised_selection
Data type: object
Unique values: 2
Missing values: 6039
under_utilised_selection
No     42718
Yes     8546
NaN     6039
Name: count, dtype: int64

==================================================
Column: under_utilisation_reason
Data type: object
Unique values: 6
Missing values: 48757
under_utilisation_reason
NaN                                        48757
Any other reason                            8138
Less discharge in the well                   211
Mechanical break down                         65
Non availability of adequate power/fuel       59
Lack of Maintenance                           48
Non-availability of finance                   25
Name: count, dtype: int64

==================================================
Column: drinking_water_purpose
Data type: object
Unique values: 2
Missing values: 0
drinking_water_purpose
No     55498
Yes     1805
Name: count, dtype: int64

==================================================
Column: captured_in_previous_census
Data type: object
Unique values: 2
Missing values: 837
captured_in_previous_census
No     55322
Yes     1144
NaN      837
Name: count, dtype: int64

In [49]:
print(df.dtypes.to_frame(name="Data_Type"))

                            Data_Type
serial_no                       int64
district_name                  object
block_tehsil_name              object
village_name                   object
latitude                      float64
...                               ...
ipu_total                     float64
under_utilised_selection       object
under_utilisation_reason       object
drinking_water_purpose         object
captured_in_previous_census    object

[63 rows x 1 columns]

# Handling Missing values

In [50]:
# Calculate missing percentage for each column
missing_percentage = df.isnull().mean() * 100

# Select columns with more than 10% missing values
cols_to_drop = missing_percentage[missing_percentage > 10].index

# Display columns that will be removed
print("Columns to drop:")
print(cols_to_drop.tolist())

# Drop the columns
# df.drop(columns=cols_to_drop, inplace=True)
df.drop(columns=["serial_no"], inplace=True)

# Check the updated dataset
print("\nNew dataset shape:", df.shape)

Columns to drop:
['dugwell_type', 'khasra_number', 'location_particulars', 'social_status', 'gender', 'finance_source1', 'finance_source2', 'not_in_use_years', 'status_reason_temporarily', 'status_reason_permanently', 'name_of_mmi_project', 'scheme_in_command_area_reason', 'under_utilised_selection', 'under_utilisation_reason']

New dataset shape: (57303, 62)

In [51]:
df.shape

(57303, 62)

In [52]:
df.head(10)

,district_name,block_tehsil_name,village_name,latitude,longitude,s_no_of_scheme,scheme_type,dugwell_type,tubewell_type,ownership,...,ipc_total,ipu_kharif_season,ipu_rabi_season,ipu_perennial_crop,ipu_other_season,ipu_total,under_utilised_selection,under_utilisation_reason,drinking_water_purpose,captured_in_previous_census
0,Goalpara,Kuchdhowa,Siluk Pt-Ii,25.956992,90.799726,1,Tube well,NaN,Medium Tube well,Govt. Owned,...,5.0,4.0,1.0,0.00,0.00,5.00,NaN,NaN,No,No
1,Kokrajhar,Kokrajhar,Bhadiaguri,26.355332,90.233585,12,Tube well,NaN,Shallow Tube well,Govt. Owned,...,1.0,0.4,0.2,0.09,0.08,0.77,NaN,NaN,No,No
2,Goalpara,Kuchdhowa,Patiarpara Pt-I,25.971319,90.917621,1,Tube well,NaN,Medium Tube well,Govt. Owned,...,4.0,4.0,0.0,0.00,0.00,4.00,NaN,NaN,No,Yes
3,Dhubri,Nayeralga,Boalkamri Pt.Iii,26.210017,90.160672,4,Tube well,NaN,Shallow Tube well,Owned by individual farmer,...,3.5,2.0,1.5,0.00,0.00,3.50,No,NaN,No,No
4,Dhubri,Nayeralga,Boalkamri Pt.Iii,26.208178,90.161543,7,Tube well,NaN,Shallow Tube well,Owned by individual farmer,...,4.5,2.5,2.0,0.00,0.00,4.50,No,NaN,No,No
5,Dhubri,Nayeralga,Boalkamri Pt.Iii,26.203070,90.158073,1,Tube well,NaN,Shallow Tube well,Owned by individual farmer,...,3.5,2.0,1.5,0.00,0.00,3.50,No,NaN,No,No
6,Dhubri,Nayeralga,Boalkamri Pt.Iii,26.202193,90.159608,2,Tube well,NaN,Shallow Tube well,Owned by individual farmer,...,3.5,2.0,1.5,0.00,0.00,3.50,No,NaN,No,No
7,Dhubri,Nayeralga,Boalkamri Pt.Iii,26.202339,90.160074,3,Tube well,NaN,Shallow Tube well,Owned by individual farmer,...,1.8,1.0,0.8,0.00,0.00,1.80,No,NaN,No,No
8,Dhubri,Nayeralga,Boalkamri Pt.Iii,26.208476,90.162682,6,Tube well,NaN,Shallow Tube well,Owned by individual farmer,...,5.0,3.0,2.0,0.00,0.00,5.00,No,NaN,No,No
9,Dhubri,Nayeralga,Boalkamri Pt.Iii,26.209554,90.161958,5,Tube well,NaN,Shallow Tube well,Owned by individual farmer,...,3.0,2.0,1.0,0.00,0.00,3.00,No,NaN,No,No

# Cleaning Cost Column

In [53]:
col = "construction_cost"

print("Data type:", df[col].dtype)
print("Missing values:", df[col].isna().sum())
print("Unique values:", df[col].nunique())
print("Zero costs:", (df[col] == 0).sum())
print("Negative costs:", (df[col] < 0).sum())

print("\nSummary statistics:")
display(df[col].describe(percentiles=[0.01, 0.25, 0.50, 0.75, 0.90, 0.95, 0.99]))

print("\nMost frequent costs:")
display(df[col].value_counts().head(15))

Data type: float64
Missing values: 0
Unique values: 1271
Zero costs: 173
Negative costs: 0

Summary statistics:

count    5.730300e+04
mean     1.577646e+05
std      6.753971e+05
min      0.000000e+00
1%       4.270000e+00
25%      1.000000e+04
50%      1.500000e+04
75%      3.500000e+04
90%      4.500000e+05
95%      6.060000e+05
99%      3.000000e+06
max      5.000000e+07
Name: construction_cost, dtype: float64

Most frequent costs:

construction_cost
10000.0     6166
12000.0     4642
15000.0     3736
20000.0     3708
5000.0      2847
8000.0      2216
6000.0      1850
25000.0     1845
30000.0     1618
35000.0     1329
9000.0      1238
606000.0    1018
100000.0     768
40000.0      701
7000.0       656
Name: count, dtype: int64

## Outliars

In [54]:
for col in ["finance_source1", "finance_source2", "ownership"]:
    print(f"\n--- {col} ---")
    result = (
        df.groupby(col, dropna=False)["construction_cost"]
        .agg(["count", "median", "mean", "max"])
        .sort_values("median", ascending=False)
    )
    display(result)

--- finance_source1 ---

                 count    median           mean         max
finance_source1
NaN              15969  200000.0  484283.822615  50000000.0
Government fund   2254  104421.0  205129.504982  10000000.0
Bank loan          159   27000.0   68447.274843   3700000.0
Money lender       252   12000.0   23067.121032    375000.0
Others            4118   12000.0   41357.909252   4000000.0
Own savings      34551   12000.0   19029.536828   1800000.0

--- finance_source2 ---

                 count   median           mean         max
finance_source2
Government fund    664  45000.0  155725.506235   4000000.0
NaN              23688  30000.0  336769.525957  50000000.0
Bank loan          160  25000.0   50716.625625    589288.0
Own savings       5297  15000.0   40809.525616  10000000.0
Others           26572  12000.0   26482.063578   7800000.0
Money lender       922  12000.0   34300.779067   1600000.0

--- ownership ---

                            count    median           mean         max
ownership
Govt. Owned                 10014  430000.0  697126.980620  50000000.0
Panchayat Owned                85   65000.0  203270.877647   2500000.0
Owned by Group of farmers    3242   25000.0  169215.208664   6000000.0
Others                       2582   15000.0   74164.095550   8000000.0
Co-Operative Owned            138   12000.0  121591.078768   3516584.0
Owned by individual farmer  41242   12000.0   31162.725314  10000000.0

In [55]:
[col for col in df.columns if "owner" in col.lower()
 or "ownership" in col.lower()]

['ownership', 'total_owners_holding']

In [56]:
df["finance_source"] = (
    df["finance_source1"]
    .combine_first(df["finance_source2"])
    .combine_first(df["ownership"])
)

# Check the result
print("Missing values:", df["finance_source"].isna().sum())
print(df["finance_source"].value_counts(dropna=False))

Missing values: 0
finance_source
Own savings                  34552
Govt. Owned                   9957
Others                        6684
Owned by Group of farmers     3221
Government fund               2257
Money lender                   252
Bank loan                      159
Co-Operative Owned             136
Panchayat Owned                 85
Name: count, dtype: int64

# removing unnecesary Colmuns

In [57]:

target = "construction_cost"

# Columns with only one unique value (including missing values)
constant_cols = [
    col for col in df.columns
    if col != target and df[col].nunique(dropna=False) <= 1
]

# Potential identifier columns: review before dropping
id_like_cols = [
    col for col in df.columns
    if any(word in col.lower() for word in
           ["id", "khasra", "name", "number"])
    and col != target
]

print("Dataset shape:", df.shape)
print("\nConstant columns (usually safe to remove):")
print(constant_cols)

print("\nPotential ID/name/number columns (review first):")
print(id_like_cols)

print("\nTarget column:", target)

Dataset shape: (57303, 63)

Constant columns (usually safe to remove):
[]

Potential ID/name/number columns (review first):
['district_name', 'block_tehsil_name', 'village_name', 'khasra_number', 'construction_subsidy', 'machinery_subsidy', 'name_of_mmi_project']

Target column: construction_cost

In [58]:
cols = ["name_of_mmi_project", "khasra_number"]

for col in cols:
    if col in df.columns:
        print(f"\n--- {col} ---")
        print("Data type:", df[col].dtype)
        print("Missing values:", df[col].isna().sum())
        print("Unique values:", df[col].nunique())
        print("\nMost frequent values:")
        print(df[col].value_counts(dropna=False).head(10))
    else:
        print(f"\n{col}: not found in df")

--- name_of_mmi_project ---
Data type: object
Missing values: 57142
Unique values: 24

Most frequent values:
name_of_mmi_project
NaN                            57142
JAMUNA IRRIGATION SCHEME          55
JAMUNA                            28
BOROLIA                           15
SONAI                             12
AMRENG                             8
BHUMKI FIS                         6
CHAMPAMATI                         5
BOROLIA IRRIGATION SCHEME          4
DHANSIRI IRRIGATION PROJECT        4
Name: count, dtype: int64

--- khasra_number ---
Data type: Int64
Missing values: 49735
Unique values: 521

Most frequent values:
khasra_number
<NA>    49735
1        2111
0         572
2         444
3         311
4         272
5         240
6         224
7         184
8         160
Name: count, dtype: Int64

In [59]:
df.drop(
    columns=["name_of_mmi_project", "khasra_number"],
    inplace=True
)

print("New dataset shape:", df.shape)

New dataset shape: (57303, 61)

In [60]:

cols = [
    "under_utilisation_reason",
    "scheme_in_command_area_reason",
    "social_status",
    "gender",
    "location_particulars"
]


"""
under_utilisation_reason fix nan 
scheme_in_command_area_reason 99% missing
"""

for col in cols:
    if col in df.columns:
        print(f"\n{'='*45}\n{col}")
        print("Data type:", df[col].dtype)
        print("Missing:", df[col].isna().sum(),
              f"({df[col].isna().mean() * 100:.2f}%)")
        print("Unique values:", df[col].nunique())
        print("\nMost frequent values:")
        print(df[col].value_counts(dropna=False).head(10))
    else:
        print(f"\n{col}: not found in df")

=============================================
under_utilisation_reason
Data type: object
Missing: 48757 (85.09%)
Unique values: 6

Most frequent values:
under_utilisation_reason
NaN                                        48757
Any other reason                            8138
Less discharge in the well                   211
Mechanical break down                         65
Non availability of adequate power/fuel       59
Lack of Maintenance                           48
Non-availability of finance                   25
Name: count, dtype: int64

=============================================
scheme_in_command_area_reason
Data type: object
Missing: 57157 (99.75%)
Unique values: 4

Most frequent values:
scheme_in_command_area_reason
NaN                                                         57157
Other reasons                                                  76
Water not available up to field from major/medium scheme       38
Water available but not adequate for irrigation                25
Water available but not useable for irrigation                  7
Name: count, dtype: int64

=============================================
social_status
Data type: object
Missing: 15942 (27.82%)
Unique values: 4

Most frequent values:
social_status
Others             31977
NaN                15942
OBC                 4455
Scheduled-tribe     2975
Scheduled-caste     1954
Name: count, dtype: int64

=============================================
gender
Data type: object
Missing: 15942 (27.82%)
Unique values: 3

Most frequent values:
gender
Male           40784
NaN            15942
Female           565
Transgender       12
Name: count, dtype: int64

=============================================
location_particulars
Data type: object
Missing: 5983 (10.44%)
Unique values: 20021

Most frequent values:
location_particulars
NaN                  5983
na                   2678
A                    1409
in filled             736
near home             524
near road             511
near house            477
NA                    463
Na                    433
NEAR PADDY FIELD      353
Name: count, dtype: int64

In [61]:
df.drop(columns=["location_particulars", "captured_in_previous_census"], inplace=True)

In [62]:
df.to_csv('tes1.csv', index=False)

In [63]:
df = pd.read_csv("tes1.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 57303 entries, 0 to 57302
Data columns (total 59 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   district_name                       57303 non-null  object
 1   block_tehsil_name                   57303 non-null  object
 2   village_name                        57303 non-null  object
 3   latitude                            57303 non-null  float64
 4   longitude                           57303 non-null  float64
 5   s_no_of_scheme                      57303 non-null  int64
 6   scheme_type                         57303 non-null  object
 7   dugwell_type                        809 non-null    object
 8   tubewell_type                       56494 non-null  object
 9   ownership                           57303 non-null  object
 10  total_owners_holding                57303 non-null  float64
 11  social_status                       41361 non-null  object
 12  gender                              41361 non-null  object
 13  commissioning_year                  57303 non-null  object
 14  scheme_depth                        57303 non-null  float64
 15  scheme_diameter                     54149 non-null  float64
 16  scheme_bore_depth                   57303 non-null  float64
 17  nearest_scheme_distance             57303 non-null  float64
 18  construction_cost                   57303 non-null  float64
 19  machinery_cost                      57303 non-null  float64
 20  maintenance_cost                    57303 non-null  float64
 21  finance_source1                     41334 non-null  object
 22  finance_source2                     33615 non-null  object
 23  construction_subsidy                57303 non-null  float64
 24  machinery_subsidy                   57303 non-null  float64
 25  scheme_status                       57303 non-null  object
 26  not_in_use_years                    6109 non-null   float64
 27  status_reason_temporarily           5342 non-null   object
 28  status_reason_permanently           767 non-null    object
 29  water_distribution_method           56536 non-null  object
 30  lifting_device_type                 56555 non-null  object
 31  energy_source                       56555 non-null  object
 32  horse_power_of_lifting_device       55384 non-null  float64
 33  pump_operating_days_kharif_season   55396 non-null  float64
 34  pump_operating_days_rabi_season     55396 non-null  float64
 35  pump_operating_days_perennial_crop  55396 non-null  float64
 36  pump_operating_days_other_season    55396 non-null  float64
 37  avg_pumping_per_day_kharif_season   55396 non-null  float64
 38  avg_pumping_per_day_rabi_season     55396 non-null  float64
 39  avg_pumping_per_day_perennial_crop  55396 non-null  float64
 40  avg_pumping_per_day_other_season    55395 non-null  float64
 41  located_in_command_area             57303 non-null  object
 42  scheme_in_command_area_reason       146 non-null    object
 43  only_recharge_ground_water          57303 non-null  object
 44  culturable_command_area             57303 non-null  float64
 45  ipc_kharif_season                   57303 non-null  float64
 46  ipc_rabi_season                     57303 non-null  float64
 47  ipc_perennial_crop                  57303 non-null  float64
 48  ipc_other_season                    57303 non-null  float64
 49  ipc_total                           57303 non-null  float64
 50  ipu_kharif_season                   57303 non-null  float64
 51  ipu_rabi_season                     57303 non-null  float64
 52  ipu_perennial_crop                  57303 non-null  float64
 53  ipu_other_season                    57303 non-null  float64
 54  ipu_total                           57303 non-null  float64
 55  under_utilised_selection            51264 non-null  object
 56  under_utilisation_reason            8546 non-null   object
 57  drinking_water_purpose              57303 non-null  object
 58  finance_source                      57303 non-null  object
dtypes: float64(33), int64(1), object(25)
memory usage: 25.8+ MB

In [64]:
df['dugwell_type'].unique()

array([nan, 'Dug well Pucca', 'Dug well Kutcha', 'Dug-cum-bore well',
       'Others'], dtype=object)

In [65]:
df.drop(columns=["gender", "social_status"], inplace=True)

In [66]:
df.head()

,district_name,block_tehsil_name,village_name,latitude,longitude,s_no_of_scheme,scheme_type,dugwell_type,tubewell_type,ownership,...,ipc_total,ipu_kharif_season,ipu_rabi_season,ipu_perennial_crop,ipu_other_season,ipu_total,under_utilised_selection,under_utilisation_reason,drinking_water_purpose,finance_source
0,Goalpara,Kuchdhowa,Siluk Pt-Ii,25.956992,90.799726,1,Tube well,NaN,Medium Tube well,Govt. Owned,...,5.0,4.0,1.0,0.00,0.00,5.00,NaN,NaN,No,Govt. Owned
1,Kokrajhar,Kokrajhar,Bhadiaguri,26.355332,90.233585,12,Tube well,NaN,Shallow Tube well,Govt. Owned,...,1.0,0.4,0.2,0.09,0.08,0.77,NaN,NaN,No,Govt. Owned
2,Goalpara,Kuchdhowa,Patiarpara Pt-I,25.971319,90.917621,1,Tube well,NaN,Medium Tube well,Govt. Owned,...,4.0,4.0,0.0,0.00,0.00,4.00,NaN,NaN,No,Govt. Owned
3,Dhubri,Nayeralga,Boalkamri Pt.Iii,26.210017,90.160672,4,Tube well,NaN,Shallow Tube well,Owned by individual farmer,...,3.5,2.0,1.5,0.00,0.00,3.50,No,NaN,No,Own savings
4,Dhubri,Nayeralga,Boalkamri Pt.Iii,26.208178,90.161543,7,Tube well,NaN,Shallow Tube well,Owned by individual farmer,...,4.5,2.5,2.0,0.00,0.00,4.50,No,NaN,No,Own savings

In [67]:
df["scheme_bore_depth"].describe()

count    57303.000000
mean         0.231128
std          5.276484
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max        450.000000
Name: scheme_bore_depth, dtype: float64

In [68]:
df['scheme_bore_depth'].value_counts().head(10)

scheme_bore_depth
0.00     57028
45.00       42
35.00       33
30.00       17
20.00       16
0.45        15
50.00       14
70.00       10
80.00       10
75.00        9
Name: count, dtype: int64

In [69]:
(df['scheme_bore_depth'] == 0).mean() * 100

np.float64(99.52009493394762)

In [70]:
df.drop(columns=['scheme_bore_depth'], inplace=True)

In [71]:
df['finance_source'] = df[['finance_source1', 'finance_source2']].apply(
    lambda row: ', '.join(row.dropna().astype(str).unique())
    if row.notna().any() else row.get('ownership', df.loc[row.name, 'ownership']),
    axis=1
)

df.drop(columns=['finance_source1', 'finance_source2'], inplace=True)

In [72]:
df.to_csv("test2.csv", index=False)

In [73]:
df = pd.read_csv("test2.csv")

In [74]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 57303 entries, 0 to 57302
Data columns (total 54 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   district_name                       57303 non-null  object
 1   block_tehsil_name                   57303 non-null  object
 2   village_name                        57303 non-null  object
 3   latitude                            57303 non-null  float64
 4   longitude                           57303 non-null  float64
 5   s_no_of_scheme                      57303 non-null  int64
 6   scheme_type                         57303 non-null  object
 7   dugwell_type                        809 non-null    object
 8   tubewell_type                       56494 non-null  object
 9   ownership                           57303 non-null  object
 10  total_owners_holding                57303 non-null  float64
 11  commissioning_year                  57303 non-null  object
 12  scheme_depth                        57303 non-null  float64
 13  scheme_diameter                     54149 non-null  float64
 14  nearest_scheme_distance             57303 non-null  float64
 15  construction_cost                   57303 non-null  float64
 16  machinery_cost                      57303 non-null  float64
 17  maintenance_cost                    57303 non-null  float64
 18  construction_subsidy                57303 non-null  float64
 19  machinery_subsidy                   57303 non-null  float64
 20  scheme_status                       57303 non-null  object
 21  not_in_use_years                    6109 non-null   float64
 22  status_reason_temporarily           5342 non-null   object
 23  status_reason_permanently           767 non-null    object
 24  water_distribution_method           56536 non-null  object
 25  lifting_device_type                 56555 non-null  object
 26  energy_source                       56555 non-null  object
 27  horse_power_of_lifting_device       55384 non-null  float64
 28  pump_operating_days_kharif_season   55396 non-null  float64
 29  pump_operating_days_rabi_season     55396 non-null  float64
 30  pump_operating_days_perennial_crop  55396 non-null  float64
 31  pump_operating_days_other_season    55396 non-null  float64
 32  avg_pumping_per_day_kharif_season   55396 non-null  float64
 33  avg_pumping_per_day_rabi_season     55396 non-null  float64
 34  avg_pumping_per_day_perennial_crop  55396 non-null  float64
 35  avg_pumping_per_day_other_season    55395 non-null  float64
 36  located_in_command_area             57303 non-null  object
 37  scheme_in_command_area_reason       146 non-null    object
 38  only_recharge_ground_water          57303 non-null  object
 39  culturable_command_area             57303 non-null  float64
 40  ipc_kharif_season                   57303 non-null  float64
 41  ipc_rabi_season                     57303 non-null  float64
 42  ipc_perennial_crop                  57303 non-null  float64
 43  ipc_other_season                    57303 non-null  float64
 44  ipc_total                           57303 non-null  float64
 45  ipu_kharif_season                   57303 non-null  float64
 46  ipu_rabi_season                     57303 non-null  float64
 47  ipu_perennial_crop                  57303 non-null  float64
 48  ipu_other_season                    57303 non-null  float64
 49  ipu_total                           57303 non-null  float64
 50  under_utilised_selection            51264 non-null  object
 51  under_utilisation_reason            8546 non-null   object
 52  drinking_water_purpose              57303 non-null  object
 53  finance_source                      57303 non-null  object
dtypes: float64(32), int64(1), object(21)
memory usage: 23.6+ MB

In [75]:
df.head()

,district_name,block_tehsil_name,village_name,latitude,longitude,s_no_of_scheme,scheme_type,dugwell_type,tubewell_type,ownership,...,ipc_total,ipu_kharif_season,ipu_rabi_season,ipu_perennial_crop,ipu_other_season,ipu_total,under_utilised_selection,under_utilisation_reason,drinking_water_purpose,finance_source
0,Goalpara,Kuchdhowa,Siluk Pt-Ii,25.956992,90.799726,1,Tube well,NaN,Medium Tube well,Govt. Owned,...,5.0,4.0,1.0,0.00,0.00,5.00,NaN,NaN,No,Govt. Owned
1,Kokrajhar,Kokrajhar,Bhadiaguri,26.355332,90.233585,12,Tube well,NaN,Shallow Tube well,Govt. Owned,...,1.0,0.4,0.2,0.09,0.08,0.77,NaN,NaN,No,Govt. Owned
2,Goalpara,Kuchdhowa,Patiarpara Pt-I,25.971319,90.917621,1,Tube well,NaN,Medium Tube well,Govt. Owned,...,4.0,4.0,0.0,0.00,0.00,4.00,NaN,NaN,No,Govt. Owned
3,Dhubri,Nayeralga,Boalkamri Pt.Iii,26.210017,90.160672,4,Tube well,NaN,Shallow Tube well,Owned by individual farmer,...,3.5,2.0,1.5,0.00,0.00,3.50,No,NaN,No,Own savings
4,Dhubri,Nayeralga,Boalkamri Pt.Iii,26.208178,90.161543,7,Tube well,NaN,Shallow Tube well,Owned by individual farmer,...,4.5,2.5,2.0,0.00,0.00,4.50,No,NaN,No,Own savings

In [76]:
cols = ['not_in_use_years', 'status_reason_temporarily', 'status_reason_permanently']

for col in cols:
    if col in df.columns:
        print(f"\n{'='*45}\n{col}")
        print("Data type:", df[col].dtype)
        print("Missing:", df[col].isna().sum(),
              f"({df[col].isna().mean() * 100:.2f}%)")
        print("Unique values:", df[col].nunique())
        print("\nMost frequent values:")
        print(df[col].value_counts(dropna=False).head(10))
    else:
        print(f"\n{col}: not found in df")

=============================================
not_in_use_years
Data type: float64
Missing: 51194 (89.34%)
Unique values: 7

Most frequent values:
not_in_use_years
NaN    51194
1.0     2225
2.0     1714
0.0     1408
3.0      240
6.0      221
5.0      198
4.0      103
Name: count, dtype: int64

=============================================
status_reason_temporarily
Data type: object
Missing: 51961 (90.68%)
Unique values: 6

Most frequent values:
status_reason_temporarily
NaN                                        51961
Any other reason                            3332
Mechanical break down                       1196
Non availability of adequate power/fuel      328
Lack of maintenance                          318
Less discharge of water                      165
Non availability of finance                    3
Name: count, dtype: int64

=============================================
status_reason_permanently
Data type: object
Missing: 56536 (98.66%)
Unique values: 7

Most frequent values:
status_reason_permanently
NaN                                                56536
Due to other reasons                                 455
Destroyed beyond repair                              251
Dried up                                              36
Due to salinity                                       14
Due to sea water intrusion                             4
Due to industrial effluents                            4
Availability of major medium irrigation project        3
Name: count, dtype: int64

In [77]:
df.drop(columns=['status_reason_permanently', "status_reason_temporarily", "not_in_use_years"], inplace=True)

In [78]:
df.loc[df['under_utilisation_reason'].isna(), 'under_utilised_selection'] = 'No'

In [79]:
df.head()

,district_name,block_tehsil_name,village_name,latitude,longitude,s_no_of_scheme,scheme_type,dugwell_type,tubewell_type,ownership,...,ipc_total,ipu_kharif_season,ipu_rabi_season,ipu_perennial_crop,ipu_other_season,ipu_total,under_utilised_selection,under_utilisation_reason,drinking_water_purpose,finance_source
0,Goalpara,Kuchdhowa,Siluk Pt-Ii,25.956992,90.799726,1,Tube well,NaN,Medium Tube well,Govt. Owned,...,5.0,4.0,1.0,0.00,0.00,5.00,No,NaN,No,Govt. Owned
1,Kokrajhar,Kokrajhar,Bhadiaguri,26.355332,90.233585,12,Tube well,NaN,Shallow Tube well,Govt. Owned,...,1.0,0.4,0.2,0.09,0.08,0.77,No,NaN,No,Govt. Owned
2,Goalpara,Kuchdhowa,Patiarpara Pt-I,25.971319,90.917621,1,Tube well,NaN,Medium Tube well,Govt. Owned,...,4.0,4.0,0.0,0.00,0.00,4.00,No,NaN,No,Govt. Owned
3,Dhubri,Nayeralga,Boalkamri Pt.Iii,26.210017,90.160672,4,Tube well,NaN,Shallow Tube well,Owned by individual farmer,...,3.5,2.0,1.5,0.00,0.00,3.50,No,NaN,No,Own savings
4,Dhubri,Nayeralga,Boalkamri Pt.Iii,26.208178,90.161543,7,Tube well,NaN,Shallow Tube well,Owned by individual farmer,...,4.5,2.5,2.0,0.00,0.00,4.50,No,NaN,No,Own savings

In [80]:
df.drop(columns=['under_utilisation_reason', "scheme_in_command_area_reason"], inplace=True)

In [81]:
df.shape

(57303, 49)

In [82]:
df.to_csv("test3.csv", index=False)

In [83]:
df = pd.read_csv("test3.csv")

In [84]:
df.head()

,district_name,block_tehsil_name,village_name,latitude,longitude,s_no_of_scheme,scheme_type,dugwell_type,tubewell_type,ownership,...,ipc_other_season,ipc_total,ipu_kharif_season,ipu_rabi_season,ipu_perennial_crop,ipu_other_season,ipu_total,under_utilised_selection,drinking_water_purpose,finance_source
0,Goalpara,Kuchdhowa,Siluk Pt-Ii,25.956992,90.799726,1,Tube well,NaN,Medium Tube well,Govt. Owned,...,0.0,5.0,4.0,1.0,0.00,0.00,5.00,No,No,Govt. Owned
1,Kokrajhar,Kokrajhar,Bhadiaguri,26.355332,90.233585,12,Tube well,NaN,Shallow Tube well,Govt. Owned,...,0.1,1.0,0.4,0.2,0.09,0.08,0.77,No,No,Govt. Owned
2,Goalpara,Kuchdhowa,Patiarpara Pt-I,25.971319,90.917621,1,Tube well,NaN,Medium Tube well,Govt. Owned,...,0.0,4.0,4.0,0.0,0.00,0.00,4.00,No,No,Govt. Owned
3,Dhubri,Nayeralga,Boalkamri Pt.Iii,26.210017,90.160672,4,Tube well,NaN,Shallow Tube well,Owned by individual farmer,...,0.0,3.5,2.0,1.5,0.00,0.00,3.50,No,No,Own savings
4,Dhubri,Nayeralga,Boalkamri Pt.Iii,26.208178,90.161543,7,Tube well,NaN,Shallow Tube well,Owned by individual farmer,...,0.0,4.5,2.5,2.0,0.00,0.00,4.50,No,No,Own savings

In [85]:
df.shape

(57303, 49)

In [86]:
dugwell_df = df[df['dugwell_type'].notna()].copy()
tubewell_df = df[df['tubewell_type'].notna()].copy()

dugwell_df.drop(columns=["scheme_type", "tubewell_type"], inplace=True)
tubewell_df.drop(columns=["scheme_type", "dugwell_type"], inplace=True)

dugwell_df.to_csv('dugwell.csv', index=False)
tubewell_df.to_csv('tubewell.csv', index=False)

In [87]:
df = pd.read_csv("tubewell.csv")

In [88]:
df.head()

,district_name,block_tehsil_name,village_name,latitude,longitude,s_no_of_scheme,tubewell_type,ownership,total_owners_holding,commissioning_year,...,ipc_other_season,ipc_total,ipu_kharif_season,ipu_rabi_season,ipu_perennial_crop,ipu_other_season,ipu_total,under_utilised_selection,drinking_water_purpose,finance_source
0,Goalpara,Kuchdhowa,Siluk Pt-Ii,25.956992,90.799726,1,Medium Tube well,Govt. Owned,0.0,Up to 2018-2019,...,0.0,5.0,4.0,1.0,0.00,0.00,5.00,No,No,Govt. Owned
1,Kokrajhar,Kokrajhar,Bhadiaguri,26.355332,90.233585,12,Shallow Tube well,Govt. Owned,0.0,During 2021-2022,...,0.1,1.0,0.4,0.2,0.09,0.08,0.77,No,No,Govt. Owned
2,Goalpara,Kuchdhowa,Patiarpara Pt-I,25.971319,90.917621,1,Medium Tube well,Govt. Owned,0.0,Up to 2018-2019,...,0.0,4.0,4.0,0.0,0.00,0.00,4.00,No,No,Govt. Owned
3,Dhubri,Nayeralga,Boalkamri Pt.Iii,26.210017,90.160672,4,Shallow Tube well,Owned by individual farmer,0.3,During 2019-2020,...,0.0,3.5,2.0,1.5,0.00,0.00,3.50,No,No,Own savings
4,Dhubri,Nayeralga,Boalkamri Pt.Iii,26.208178,90.161543,7,Shallow Tube well,Owned by individual farmer,1.0,During 2022-2023,...,0.0,4.5,2.5,2.0,0.00,0.00,4.50,No,No,Own savings

In [89]:
# droping unnecesary columns

df.drop(columns=["s_no_of_scheme", "machinery_cost", "construction_subsidy", "machinery_subsidy", "maintenance_cost", "scheme_status"], inplace=True)

In [90]:
df.to_csv('tubewell1.csv', index=False)

In [91]:
df = pd.read_csv("tubewell1.csv")

In [92]:
pd.crosstab(df['ownership'], df['total_owners_holding'])

total_owners_holding,0.000,0.001,0.010,0.020,0.030,0.040,0.050,0.060,0.070,0.080,...,147.000,189.000,200.000,220.000,224.000,250.000,322.000,335.000,6000.000,9000.000
ownership,,,,,,,,,,,,,,,,,,,,,
Co-Operative Owned,134,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Govt. Owned,9875,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Others,2355,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Owned by Group of farmers,3198,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Owned by individual farmer,0,3,13,6,2,6,7,2,1,3,...,1,1,1,4,1,2,1,1,1,1
Panchayat Owned,67,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [93]:
df.groupby(['ownership', 'total_owners_holding'])['construction_cost'].agg(
    ['mean', 'count']
).round(2)

                                                      mean  count
ownership                  total_owners_holding
Co-Operative Owned         0.000                 124153.50    134
Govt. Owned                0.000                 704045.41   9875
Others                     0.000                  75792.86   2355
Owned by Group of farmers  0.000                 170288.52   3198
Owned by individual farmer 0.001                     11.33      3
...                                                    ...    ...
                           322.000                15000.00      1
                           335.000                 7000.00      1
                           6000.000                5000.00      1
                           9000.000                6500.00      1
Panchayat Owned            0.000                 228792.31     67

[304 rows x 2 columns]

In [94]:
print(df[['total_owners_holding', 'construction_cost']].corr())

                      total_owners_holding  construction_cost
total_owners_holding              1.000000          -0.006017
construction_cost                -0.006017           1.000000

In [96]:
cols = [
    "under_utilisation_reason",
    "scheme_in_command_area_reason",
    "social_status",
    "gender",
    "location_particulars"
]

summary = pd.DataFrame({
    "missing_count": df[cols].isna().sum(),
    "missing_percent": (df[cols].isna().mean() * 100).round(2),
    "unique_values": df[cols].nunique()
}).sort_values("missing_percent", ascending=False)

display(summary)

KeyError: "None of [Index(['under_utilisation_reason', 'scheme_in_command_area_reason',\n       'social_status', 'gender', 'location_particulars'],\n      dtype='object')] are in the [columns]"